### ISSUE TITLE
Metodologia do projeto

### ISSUE THREAD

**Issue by Eugeniosales** [UnBArqDsw/2020.1_G9_WoCo#19]
### Descrição:
Elaborar artefatos para descrição da metodologia adotada.

### Tarefas
- [x] Desenho detalhado da metodologia do projeto, utilizando a notação BMPN.
- [x] Pequeno áudio procurando explicar em linhas gerais a metodologia utilizada.

**Comment by Eugeniosales** [comment]
@davialvb @Mexazonic @ZarathosDeath @WeillerFernandes. Sobre as metodologias, acho melhor adotarmos Scrum e XP tendo em vista o workflow que já vínhamso trabalhando desde antes da paralisação. RUP é interessante, mas Scrum se aplica melhor para o nosso planejamento, o que acham?

**Comment by WeillerFernandes** [comment]
@Eugeniosales Sim, acredito que a melhor opção seja adotar uma metodologia híbrida, mesclando os elementos dessas outras metodologias que mais se adequarem ao nosso projeto.

**Comment by Mexazonic** [comment]
@Eugeniosales concordo que essa mescla beneficia o grupo e o projeto, ainda mais com uma equipe em menor número, fica mais tranquilo acompanhar e gerenciar usando ambas metodologias.

**Comment by Eugeniosales** [comment]
Usaremos Scrum e XP então.
