### ISSUE TITLE
Diagrama de pacotes

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#24]
### Descrição:
Elaborar Diagrama de pacotes.

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Diagrama de pacotes
- [x] Versionar
- [x] Subir para o github pages

**Comment by ZarathosDeath** [comment]
PR do Diagrama de Pacotes aceito e issue considerada finalizada
