### ISSUE TITLE
Diagrama de classes

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#25]
### Descrição:
Elaborar Diagrama de classes

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Diagrama de classes
- [x] Versionar
- [x] Subir para o github pages

**Comment by ZarathosDeath** [comment]
Diagrama de Classes UML enviado para revisão

**Comment by Mexazonic** [comment]
Diagrama de Classes efetuado com sucesso
