### ISSUE TITLE
Diagrama de Dependência & Associação

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#27]
### Descrição:
Diagrama de Dependência & Associação

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Elaborar Diagrama de Dependência & Associação
- [ ] Versionar
- [ ] Subir para o github pages

**Comment by ZarathosDeath** [comment]
Diagrama de classes UML atualizado com relacionamento das classes
