### ISSUE TITLE
Diagrama de Sequência

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#31]
### Descrição:
Elaborar Diagrama de Sequência

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Diagrama de Sequência
- [x] Versionar
- [x] Subir para o github pages

**Comment by ZarathosDeath** [comment]
PR do Diagrama de Sequência foi aprovado, e issue considerada finalizada.
