### ISSUE TITLE
Diagrama de Atividades

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#33]
### Descrição:
Elaborar Diagrama de Atividades

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Diagrama de Atividades
- [x] Versionar
- [x] Subir para o github pages

**Comment by ZarathosDeath** [comment]
Diagrama de Atividades feito e revisado de acordo com a documentação da matéria
