### ISSUE TITLE
Diagrama de Estados

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#34]
### Descrição:
Elaborar Diagrama de Estados

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Diagrama de Estados
- [x] Versionar
- [x] Subir para o github pages

**Comment by ZarathosDeath** [comment]
PR aceito e issue considerada finalizada
