### ISSUE TITLE
Estudo GOF Criacional

### ISSUE THREAD

**Issue by Eugeniosales** [UnBArqDsw/2020.1_G9_WoCo#46]
### Descrição:
Elaborar documento com os padrões do GOF Criacional delineados e correlacionar com os artefatos de modelagem do projeto.

### Padões
Para ser aceita a tarefa deve conter:
- [x] Abstract factory
- [x] Factory method
- [x] Singleton

**Comment by ZarathosDeath** [comment]
Adicionado o Singleton e o Abstract Factory. Enviado para Revisão
