### ISSUE TITLE
Estudo GOF Estrutural

### ISSUE THREAD

**Issue by Eugeniosales** [UnBArqDsw/2020.1_G9_WoCo#47]
### Descrição:
Elaborar documento com os padrões do GOF Estrutural delineados e correlacionar com os artefatos de modelagem do projeto.

### Padões
Para ser aceita a tarefa deve conter:
- [x] Adapter
- [x] Decorator
- [x] Composite
- [x] Facade

**Comment by ZarathosDeath** [comment]
Documento de estudo finalizado e enviado para revisão
