### ISSUE TITLE
Criação de Quadro do conhecimento

### ISSUE THREAD

**Issue by Eugeniosales** [UnBArqDsw/2020.1_G9_WoCo#65]
### Descrição:
Criação de Quadro do conhecimento para norteamento dos pareamentos do XP.

### Checklist
Para ser aceita a tarefa deve conter:
- [x] Criação de tabela excel do quadro do conhecimento

**Comment by davialvb** [comment]
Quadro criado, [link](https://docs.google.com/spreadsheets/d/1fAJ30dSfyClurf6YIRNUxLHOUyd8kS5gn-5dVUBYkQs/edit?usp=sharing) para acesso

**Comment by Eugeniosales** [comment]
A cada sprint, será feita um acompanhamento acerca do quadro para guiar os pareamentos e por consequência elevar o conhecimento do grupo de forma homogênea.
