### ISSUE TITLE
Fazer Roadmap do Produto

### ISSUE THREAD

**Issue by davialvb** [UnBArqDsw/2020.1_G9_WoCo#9]
### Descrição:
Elaborar Roadmap do Produto de baixa fidelidade para a aplicação WoCo

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Elaborar Roadmap do Produto
- [x] Versionar
- [x] Subir para o github pages

**Comment by Eugeniosales** [comment]
Essa issue será continuada na próxima sessão do conteúdo.

**Comment by Eugeniosales** [comment]
Descontinuada
